#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
# HelmiWrt OS by helmiau.com
#=================================================

name: Backup Last HelmiWrt 18.06

on:
  workflow_dispatch:
  #schedule:
  #  - cron: 0 17 * * *
  # watch:
  #   types: started

env:
  #Workflow Infos
  DIY_SH: scripts/runme.sh
  FIRMWARE_RELEASE_UPLOAD: true
  TZ: Asia/Jakarta

jobs:
  armvirt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sed -i -e 's/\r$//' $(grep -rli "a" "$GITHUB_WORKSPACE/scripts")
          chmod +x $GITHUB_WORKSPACE/scripts/free_disk_space.sh && $GITHUB_WORKSPACE/scripts/free_disk_space.sh
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rdate squashfs-tools $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          docker image prune -a -f

      - name: Download Firmware
        id: donlot
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/$DIY_SH armvirt
          echo "WORKSPACE=$GITHUB_WORKSPACE/maknyus" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        uses: ncipollo/release-action@v1.12.0
        if: env.FIRMWARE_RELEASE_UPLOAD == 'true' && steps.donlot.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: Last HelmiWrt OS 18.06 2023.04.11
          tag: helmiwrt-2023.04.11
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.WORKSPACE }}/*

  rpirockchip:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sed -i -e 's/\r$//' $(grep -rli "a" "$GITHUB_WORKSPACE/scripts")
          chmod +x $GITHUB_WORKSPACE/scripts/free_disk_space.sh && $GITHUB_WORKSPACE/scripts/free_disk_space.sh
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rdate squashfs-tools $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          docker image prune -a -f

      - name: Download Firmware
        id: donlot
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/$DIY_SH "bcm27xx\|rockchip"
          echo "WORKSPACE=$GITHUB_WORKSPACE/maknyus" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        uses: ncipollo/release-action@v1.12.0
        if: env.FIRMWARE_RELEASE_UPLOAD == 'true' && steps.donlot.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: Last HelmiWrt OS 18.06 2023.04.11
          tag: helmiwrt-2023.04.11
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.WORKSPACE }}/*

  stb:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sed -i -e 's/\r$//' $(grep -rli "a" "$GITHUB_WORKSPACE/scripts")
          chmod +x $GITHUB_WORKSPACE/scripts/free_disk_space.sh && $GITHUB_WORKSPACE/scripts/free_disk_space.sh
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rdate squashfs-tools $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          docker image prune -a -f

      - name: Download Firmware
        id: donlot
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/$DIY_SH "s905\|s912\|s922"
          echo "WORKSPACE=$GITHUB_WORKSPACE/maknyus" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        uses: ncipollo/release-action@v1.12.0
        if: env.FIRMWARE_RELEASE_UPLOAD == 'true' && steps.donlot.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: Last HelmiWrt OS 18.06 2023.04.11
          tag: helmiwrt-2023.04.11
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.WORKSPACE }}/*

  sunxi:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sed -i -e 's/\r$//' $(grep -rli "a" "$GITHUB_WORKSPACE/scripts")
          chmod +x $GITHUB_WORKSPACE/scripts/free_disk_space.sh && $GITHUB_WORKSPACE/scripts/free_disk_space.sh
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rdate squashfs-tools $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          docker image prune -a -f

      - name: Download Firmware
        id: donlot
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/$DIY_SH sunxi
          echo "WORKSPACE=$GITHUB_WORKSPACE/maknyus" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        uses: ncipollo/release-action@v1.12.0
        if: env.FIRMWARE_RELEASE_UPLOAD == 'true' && steps.donlot.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: Last HelmiWrt OS 18.06 2023.04.11
          tag: helmiwrt-2023.04.11
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.WORKSPACE }}/*

  x86:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sed -i -e 's/\r$//' $(grep -rli "a" "$GITHUB_WORKSPACE/scripts")
          chmod +x $GITHUB_WORKSPACE/scripts/free_disk_space.sh && $GITHUB_WORKSPACE/scripts/free_disk_space.sh
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rdate squashfs-tools $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          docker image prune -a -f

      - name: Download Firmware
        id: donlot
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/$DIY_SH x86
          echo "WORKSPACE=$GITHUB_WORKSPACE/maknyus" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload Firmware
        uses: ncipollo/release-action@v1.12.0
        if: env.FIRMWARE_RELEASE_UPLOAD == 'true' && steps.donlot.outputs.status == 'success' && !cancelled()
        with:
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          name: Last HelmiWrt OS 18.06 2023.04.11
          tag: helmiwrt-2023.04.11
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.WORKSPACE }}/*
